### PR TITLE
Created markdown files using pandoc

### PR DESCRIPTION
**Pull request by s093294**
```
C:\dev\github\azure-quickstart-templates\acs-docs>pandoc -s "130 Increasing the Agent Count.docx" -t markdown_github -o "130 Increasing the Agent Count.m
d" --extract-media=images/130
pandoc: extracting images/130\media\image1.png
pandoc: extracting images/130\media\image2.png
pandoc: extracting images/130\media\image3.png

C:\dev\github\azure-quickstart-templates\acs-docs>pandoc -s "120 Application Management through the REST API.docx" -t markdown_github -o "120 Application
 Management through the REST API.md" --extract-media=images/120

C:\dev\github\azure-quickstart-templates\acs-docs>pandoc -s "110 Application Management through the UI.docx" -t markdown_github -o "110 Application Manag
ement through the UI.md" --extract-media=images/110
pandoc: extracting images/110\media\image1.png
pandoc: extracting images/110\media\image10.png
pandoc: extracting images/110\media\image11.png
pandoc: extracting images/110\media\image12.png
pandoc: extracting images/110\media\image2.png
pandoc: extracting images/110\media\image3.png
pandoc: extracting images/110\media\image4.png
pandoc: extracting images/110\media\image5.png
pandoc: extracting images/110\media\image6.png
pandoc: extracting images/110\media\image7.png
pandoc: extracting images/110\media\image8.png
pandoc: extracting images/110\media\image9.png

C:\dev\github\azure-quickstart-templates\acs-docs>pandoc -s "108 Connecting to Orchestration REST API.docx" -t markdown_github -o "108 Connecting to Orch
estration REST API.md" --extract-media=images/108
pandoc: extracting images/108\media\image1.png
pandoc: extracting images/108\media\image2.png
pandoc: extracting images/108\media\image3.png
pandoc: extracting images/108\media\image4.png
pandoc: extracting images/108\media\image5.png
pandoc: extracting images/108\media\image6.png

C:\dev\github\azure-quickstart-templates\acs-docs>pandoc -s "105 Creating a Service using the Command Line.docx" -t markdown_github -o "105 Creating a Se
rvice using the Command Line.md" --extract-media=images/105
pandoc: extracting images/105\media\image1.png
```

### CODE REVIEW

**Comment by rgardler** [comment]
@s093294 There are conflicts with this merge, can you please rebase.

**Comment by s093294** [comment]
@rgardler Sorry - i reached my limits within git. Not exactly sure what I need to do and was not able to google it. I dont fully understand what it is that is conflicting.

**Comment by rgardler** [comment]
@s093294 fair enough I'll resolve it myself. Thanks for your contribution

**Comment by s093294** [comment]
Thanks - i did find some good information on rebase and understands it for next time. 
https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

**Pull request merged**
